name = "Soberana Server"
author = "soberanacraft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4bb9416ab6eb7d6707d80f435f46caffd5be61c9c37e94311b4fe048a50b2b9"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"
